print("Welcome to your adventure simulator")
print("I am going to ask you a bunch of questions and then create an epic story with you as the star!")
print()
Name = input("What is your name? ")
Enemy = input("What is your worst enemy's name? ")
Superpower = input("What is your superpower? ")
Live = input("Where do you live? ")
Food = input("What is your favorite food? ")
print()
print("Hello\033[32m", Name, "\033[0mYour ability to\033[33m", Superpower, "\033[0mwill make sure you never have to look at\033[36m", Enemy, "\033[0magain. Go eat\033[35m", Food, "\033[0mas you walk down the streets of\033[34m", Live, "\033[0mand use\033[33m", Superpower, "\033[0mfor good and not for evil!")